### ISSUE TITLE
[Feature request] Sublist in list

### ISSUE THREAD

**Issue by jckbrtn** [CarnetApp/CarnetDocumentation#76] opened 2019-09-10 12:29 UTC
o	List 1
   o	Item 1.1
   o	Item 1.2
   o	Item 1.3
   o	Item 1.4
   o	Item 1.xx
o	List 2
   o	Item 2.1
   o	Item 2.2
   o	Item 2.3
   o	Item 2.4
   o	Item 2.xx
o	List xx
   o	Item xx.1
   o	Item xx.2
   o	…

**Comment by viktor-c** [comment] 2020-04-20 21:29
I find it useful as well, since I use it to do my shopping list as well. This way I could group stuff together to be more organized when buying stuff.
Would be nice to see this!

**Comment by zinzolin** [comment] 2021-09-29 09:21
@ChangelinPipou This thread is a duplicate of which other one? Not finding, I am commenting here.

I would love to see that feature too.

A first a simple version of it could be that some text after a dash and a space a the beginning a line would be recognized as a list. And pressing enter would create another list item. Like in this editor, for example.

List subitems could also be great improvement. But first things first.

**Closed** 2021-09-29 09:27 UTC
Labels: duplicate, enhancement
